### ISSUE TITLE
WRONG LOGIC FOR BALANCED PARANTHESIS 

### ISSUE THREAD

**Issue by GauravWalia19** [TechOUs/Data-Structures#14]
* File Name is ironical
* Logic  is wrong as it should display whether the expression is balanced or not but its not doing so....
* File name should be using of stack in case of balanced paranthesis.
* **Use of stdio.h and malloc.h using in the cpp code**
* **There should be no empty file for evaluation of expressions**

**Comment by anarchymonkey** [comment]
True, thank you for the insight but the code is not complete yet.

**Comment by GauravWalia19** [comment]
You should put the full code as Half code is useless.

**Comment by GauravWalia19** [comment]
# BUG FIXED...

**Comment by anarchymonkey** [comment]
Enter a pull request so that we can merge it. Thank you for your contributions
