### ISSUE TITLE
HacktoberFest20

### ISSUE THREAD

**Issue by ifenil** [TechOUs/Data-Structures#56]
## Name the program which you are adding

Graph and its representation

## Programming Language you will code

Java

## YOU ARE

a student 

## GITHUB USERNAME

@ifenil

**Comment by GauravWalia19** [comment]
Okay you can send us Pull Request

**Comment by ifenil** [comment]
What is the issue

**Comment by ifenil** [comment]
Why it shows closed 😭

**Comment by GauravWalia19** [comment]
Here issues are just for tracking only your PR is merged please have a look.

**Comment by ifenil** [comment]
So, what I have to do now,
I googled it but not find any solution,
btw Thanks for your time.
