### ISSUE TITLE
HacktoberFest20

### ISSUE THREAD

**Issue by kritika2311** [TechOUs/Data-Structures#73]
## Name the program which you are adding

added program for list in python

## Programming Language you will code

Python

## YOU ARE

a student 

## GITHUB USERNAME

kritika2311

**Comment by GauravWalia19** [comment]
Add the you python code with the .py extension and under **Data-Structures / LISTS / INBUILT / ARRAYLIST / PYTHON/ Your Code file**

**Comment by kritika2311** [comment]
Okay
